const escapeHtml = (value = "") =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");

const compactDate = (value) => {
  const [, month, day] = value.split("-").map(Number);
  return `${month}.${day}`;
};

const displayEndDate = (value) => {
  const [year, month, day] = value.split("-").map(Number);
  return `${year}.${month}.${day}`;
};

const isPast = (date, today) => date < today;

const pageHead = ({ site, title, description, ogDescription, path = "/", type = "website", stylesheet }) => `<!DOCTYPE html>
<!-- Generated by scripts/build.mjs. Edit src/content.mjs or src/render.mjs instead. -->
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<meta name="description" content="${escapeHtml(description)}">
<link rel="canonical" href="${site.url}${path}">
<meta property="og:title" content="${escapeHtml(title)}">
<meta property="og:description" content="${escapeHtml(ogDescription ?? description)}">
<meta property="og:url" content="${site.url}${path}">
<meta property="og:type" content="${type}">
<meta property="og:image" content="${site.url}/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Black+Han+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css">
<link rel="stylesheet" href="${stylesheet}">
</head>`;

const wordmark = (site) => `${site.name.slice(0, 2)}<span class="a">A</span>${site.name.slice(3)}`;

const renderPick = (pick, { archived = false, today }) => {
  const done = isPast(pick.endDate, today);
  const classes = ["pick", done ? "done" : ""].filter(Boolean).join(" ");
  const tag = archived ? (done ? "마감" : "진행 중") : pick.tag;
  const tagClasses = ["tag", archived ? (done ? "done" : "live") : ""].filter(Boolean).join(" ");

  return `<a class="${classes}" href="${escapeHtml(pick.url)}" target="_blank" rel="noopener">
        <span class="${tagClasses}">${escapeHtml(tag)}</span>
        <div class="venue">${escapeHtml(pick.venue)}</div>
        <h3>${escapeHtml(pick.title)}</h3>
        <p>${escapeHtml(pick.description)}</p>
        <div class="meta">~${displayEndDate(pick.endDate)} · ${escapeHtml(pick.price)}</div>
      </a>`;
};

export const renderHome = ({ site, episodes, weeklyIssues, today }) => {
  const featured = episodes.find((episode) => episode.id === site.featuredEpisodeId);
  const archiveEpisodes = episodes
    .filter((episode) => episode.id !== featured.id)
    .sort((a, b) => b.number.localeCompare(a.number))
    .slice(0, 3);
  const [currentIssue, ...pastIssues] = weeklyIssues;
  const archivedPicks = pastIssues.flatMap((issue) => issue.picks);

  return `${pageHead({
    site,
    title: site.title,
    description: site.description,
    ogDescription: site.ogDescription,
    stylesheet: "/assets/home.css"
  })}
<body>
<a class="skip-link" href="#content">본문으로 바로가기</a>

<header class="masthead">
  <div class="wrap">
    <div class="top">
      <span>${escapeHtml(site.eyebrow)}</span>
      <span>${escapeHtml(site.updatedLabel)}</span>
    </div>
    <div class="title">
      <div class="wordmark">${wordmark(site)}</div>
      <div class="tagline">${escapeHtml(site.tagline)}</div>
    </div>
    <nav aria-label="주요 메뉴">
      <a class="hot" href="#weekly">이번 주 전시</a>
      <a href="#archive">3분 만에 아는 척</a>
      <a href="#about">소개</a>
      <a href="${site.newsletterUrl}" target="_blank" rel="noopener">뉴스레터</a>
    </nav>
  </div>
</header>

<main id="content">
  <div class="wrap">
    <section class="featured" aria-labelledby="featured-title">
      <div class="img">
        <img src="${featured.image.src}" alt="${escapeHtml(featured.image.alt)}" width="1000" height="750">
      </div>
      <div>
        <span class="label">이번 주 커버스토리</span>
        <h1 id="featured-title">${featured.titleHtml}</h1>
        <p class="lede">${escapeHtml(featured.lede)}</p>
        <p class="byline"><b>${featured.minutes}분</b> 소요 · ${escapeHtml(featured.artist)} · ${escapeHtml(featured.movement)} · EP.${featured.number}</p>
        <a class="read" href="${featured.id}.html">기사 읽기 →</a>
      </div>
    </section>

    <section id="archive">
      <div class="sec-label">
        <h2><span class="red">3분 만에</span> 아는 척</h2>
        <div class="rule"></div>
        <span class="more">최신 ${episodes.length}편</span>
      </div>
      <div class="grid">
        ${archiveEpisodes.map((episode) => `<a class="story" href="${episode.id}.html">
          <div class="img"><img src="${episode.image.cardSrc}" alt="${escapeHtml(episode.image.alt)}" loading="lazy" width="800" height="550"></div>
          <span class="ep">EP.${episode.number} — ${escapeHtml(episode.artistKey)}</span>
          <h3>${escapeHtml(episode.title)}</h3>
          <p>${escapeHtml(episode.summary)}</p>
          <span class="min"><b>${episode.minutes}분</b> · ${escapeHtml(episode.cardMovement ?? episode.movement)}</span>
        </a>`).join("\n")}
      </div>
    </section>
  </div>

  <section class="weekly" id="weekly" aria-labelledby="weekly-title">
    <div class="wk">
      <div class="wk-head">
        <div>
          <span class="series">전시줍줍 #${currentIssue.number}</span>
          <h2 id="weekly-title">이번 주 전시 <span class="y">줍줍</span></h2>
          <p>${escapeHtml(currentIssue.headline)}. 매주 금요일 이 자리에서 갱신돼요.</p>
        </div>
        <div class="stamp">${escapeHtml(currentIssue.label)}</div>
      </div>
      <div class="picks">
        ${currentIssue.picks.map((pick) => renderPick(pick, { today })).join("\n")}
      </div>
    </div>

    <div class="wk-arch">
      <div class="arch-head">
        <h3>지난 줍줍 아카이브</h3>
        <div class="rule"></div>
        <span class="note">진행 중 먼저 · 마감은 흐리게</span>
      </div>
      <div class="picks arch">
        ${archivedPicks
          .sort((a, b) => Number(isPast(a.endDate, today)) - Number(isPast(b.endDate, today)))
          .map((pick) => renderPick(pick, { archived: true, today }))
          .join("\n")}
      </div>
    </div>
  </section>

  <div class="wrap">
    <section id="about" class="about">
      <div class="label">ABOUT CRACKERS</div>
      <h2>아는 척 하지 마세요.<br>저희가 대신 깹니다.</h2>
      <p>CRACKERS는 <strong>전시 1도 모르는 사람을 위한 서울 전시 입문 가이드</strong>입니다. 전시장에서 30초 만에 나온 경험, 당신 잘못이 아니에요. 아무도 쉽게 안 알려줘서 그런 겁니다. 저희는 정보 대신 <strong>관점과 안심</strong>을 팝니다.</p>
      <div class="rules">
        <div class="rule"><div class="n">01</div><h3>솔직하게</h3><p>"이건 좀 별로"까지 말합니다.</p></div>
        <div class="rule"><div class="n">02</div><h3>쉽게</h3><p>전문용어는 버립니다.</p></div>
        <div class="rule"><div class="n">03</div><h3>편들어주기</h3><p>몰라도 괜찮아, 가 기본값.</p></div>
      </div>
    </section>
  </div>

  <section class="news">
    <div class="in">
      <h2>전시 소식, 메일로 깨서 드립니다</h2>
      <p>매주 서울 전시 픽과 3분 명화 해설. 좋은 척 안 하고, 몰라도 안 쪽팔리게.</p>
      <a href="${site.newsletterUrl}" target="_blank" rel="noopener">무료로 구독하기</a>
    </div>
  </section>
</main>

<footer>
  <div class="in">
    <span class="wordmark">${wordmark(site)}</span>
    <div class="links">
      <a href="${site.instagramUrl}" target="_blank" rel="noopener">Instagram</a>
      <a href="${site.threadsUrl}" target="_blank" rel="noopener">Threads</a>
      <a href="${site.newsletterUrl}" target="_blank" rel="noopener">Newsletter</a>
    </div>
    <span>© 2026 ${site.name} · ${site.email}</span>
  </div>
</footer>
</body>
</html>
`;
};

const renderBlock = (block) => {
  if (block.type === "paragraph") return `<p>${block.html}</p>`;
  if (block.type === "heading") return `<h2>${escapeHtml(block.text)}</h2>`;
  if (block.type === "pull") return `<div class="pull">${block.html}</div>`;
  if (block.type === "figure") {
    return `<figure class="artwork secondary">
      <img src="${escapeHtml(block.src)}" alt="${escapeHtml(block.alt)}" loading="lazy">
      <figcaption>${escapeHtml(block.caption)}</figcaption>
    </figure>`;
  }
  throw new Error(`알 수 없는 글 블록 유형: ${block.type}`);
};

export const renderEpisode = ({ site, episode, previous, next }) => {
  const path = `/${episode.id}`;
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: episode.title,
    description: episode.seoDescription,
    image: episode.image.src,
    datePublished: `${episode.published.replace(".", "-")}-01`,
    author: { "@type": "Organization", name: site.name },
    publisher: { "@type": "Organization", name: site.name },
    mainEntityOfPage: `${site.url}${path}`
  };

  return `${pageHead({
    site,
    title: `${episode.title} | ${site.name}`,
    description: episode.seoDescription,
    ogDescription: episode.ogDescription,
    path,
    type: "article",
    stylesheet: "/assets/article.css"
  })}
<body>
<a class="skip-link" href="#article">본문으로 바로가기</a>
<div class="topbar">
  <a class="logo wordmark" href="index.html">${wordmark(site)}</a>
  <a class="back" href="index.html#archive">← 아카이브로</a>
</div>

<main>
  <article id="article">
    <span class="ep-label">3분 만에 아는 척 — EP.${episode.number}</span>
    <h1>${episode.titleHtml}</h1>
    <div class="meta">
      <span><b>${episode.minutes}분</b> 소요</span>
      <span>${escapeHtml(episode.artist)}</span>
      <span>${escapeHtml(episode.movement)}</span>
      <span>${escapeHtml(episode.published)}</span>
    </div>

    <figure class="artwork">
      <img src="${episode.image.src}" alt="${escapeHtml(episode.image.alt)}">
      <figcaption>${escapeHtml(episode.image.caption)}</figcaption>
    </figure>

    ${episode.blocks.map(renderBlock).join("\n")}

    <div class="usebox">
      <div class="t">전시장에서 써먹기 🔖</div>
      <p>${episode.usebox}</p>
    </div>

    <p class="instagram-note">카드뉴스 3분 요약은 <a href="${episode.instagramUrl}" target="_blank" rel="noopener">인스타(@crackers.kr)</a>에서 볼 수 있어요. 다음 그림은 댓글로 신청받아요.</p>
${episode.sources?.length ? `    <aside class="sources"><h2>참고한 자료</h2><ul>${episode.sources.map((source) => `<li><a href="${source}" target="_blank" rel="noopener">${new URL(source).hostname}</a></li>`).join("")}</ul></aside>` : ""}
  </article>

  <nav class="next" aria-label="에피소드 이동">
    ${previous ? `<a href="${previous.id}.html">← 이전 — EP.${previous.number} ${escapeHtml(previous.artist)}, ${escapeHtml(previous.title.split(",")[0])}</a>` : "<span></span>"}
    ${next ? `<a href="${next.id}.html">다음 — EP.${next.number} ${escapeHtml(next.artist)}, ${escapeHtml(next.title.split(",")[0])} →</a>` : "<span></span>"}
  </nav>

  <section class="cta">
    <div class="in">
      <h2>다음 그림도 깨드릴까요?</h2>
      <p>매주 한 점씩, 3분 만에 아는 척할 수 있게 메일로 보내드립니다.</p>
      <a href="${site.newsletterUrl}" target="_blank" rel="noopener">무료로 구독하기</a>
    </div>
  </section>
</main>

<footer>© 2026 ${site.name} · 문화의 껍질을 깨는 미디어 · <a href="${site.instagramUrl}">@crackers.kr</a></footer>
<script type="application/ld+json">${JSON.stringify(articleSchema).replaceAll("<", "\\u003c")}</script>
</body>
</html>
`;
};

export const renderSitemap = ({ site, episodes }) => `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${site.url}/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url>
  ${episodes.map((episode) => `<url><loc>${site.url}/${episode.id}</loc><changefreq>monthly</changefreq><priority>0.8</priority></url>`).join("\n  ")}
</urlset>
`;
